---
- name: Playbook to Crearte user and password
  hosts: all
  become: true
  tasks:

    - name: Mention the include var file
      ansible.builtin.include_vars:
        file: information.yaml

    - name: Create user and password
      ansible.builtin.user:
        name: "{{ bedrockers.rock_user }}"
        password: "{{ bedrockers.rock_pass | password_hash('sha512') }}"
        update_password: on_create 
        state: present
